# Generated by Django 4.1.6 on 2023-02-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTercerPreEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='inversores',
        ),
    ]
